
train_file: ['../data/mimic_train.json']
bert_config: 'configs/config_bert.json'

image_res: 256
vision_width: 768
embed_dim: 256
batch_size: 32
temp: 0.07
mlm_probability: 0.15
queue_size: 65536
momentum: 0.995
alpha: 0.4

optimizer: {opt: adamW, lr: 0.00001, weight_decay: 0.02}
schedular: {sched: cosine, lr: 0.00001, epochs: 60, min_lr: 0.000001, decay_rate: 1, warmup_lr: 0.000001, warmup_epochs: 5, cooldown_epochs: 0}
